Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [3]:
import numpy as np
list_ = ['1','2','3','4','5' ]

In [4]:
array_list = np.array(object = list_)

In [5]:
print("data type of list_:" ,type(list_[0]))
print("data type of array_list:", array_list.dtype)

data type of list_: <class 'str'>
data type of array_list: <U1


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [6]:
import numpy as np
list_ = ['1','2','3','4','5' ]
array_list = np.array(object = list_)
print("data type of element in lit_:")
for element in list_:
    print(type(element)) 
print("data type of element in list")
for element in array_list:
    print(type(element))

data type of element in lit_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
data type of element in list
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [7]:
array_list = np.array(object = list_, dtype = int)

In [8]:
list_ = ['1' ,'2' ,'3' ,'4' ,'5']
array_list = np.array(object=list_, dtype=int)

In [9]:
print("data type of element in list_:")
for element in list_:
    print(type(element))
print("data type of element in list")
for element in array_list:
    print(type(element))

data type of element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
data type of element in list
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [10]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [13]:
ar = np.array(num_list)

In [14]:
ar

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
ar.shape

(2, 3)

In [16]:
ar.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [13]:
import numpy as np
import numpy.matlib as nm

In [14]:
a = np.matrix(3*3)

In [15]:
a

matrix([[9]])

In [5]:
np.asanyarray(a)

matrix([[9]])

In [9]:
nm.zeros(3*3)

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
a.shape

(1, 1)

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [18]:
import numpy as np

In [23]:
np.zeros(shape=(5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])